### ISSUE TITLE
[FEATURE REQUEST] add default headers to config

### ISSUE THREAD

**Issue by olexsmir** [oysandvik94/curl.nvim#15]
Hey :wave: 

I think it would be great to see the response status code and headers in the Output window

**Comment by oysandvik94** [comment]
Hi!

Like in curl, you can use the -i flag to output headers, and they will be displayed in the output buffer.

The reason this is not on by default is because I want to keep the experience as close to stock curl as possible, and personally I usually only include headers if I need to see them.

However, if you prefer to see then all the time, I can consider adding a configuration option where you can specify default headers, such as "-i".

**Comment by olexsmir** [comment]
Thanks for the response.

I would like to see the ability to specify default arguments for curl!

**Comment by oysandvik94** [comment]
Great! I reworded the issue to reflect that.

Should be simple, but I will get started after I'm done with the global persistence issue.

**Comment by oysandvik94** [comment]
Done, see: https://github.com/oysandvik94/curl.nvim?tab=readme-ov-file#configuration

For your case:
```lua
local curl = require("curl").setup()

curl.setup {
  -- Table of strings to specify default headers to be included in each request, i.e. "-i"
  default_flags = { "-i" },
}
```
