### ISSUE TITLE
feature request: auto-completion for custom curls

### ISSUE THREAD

**Issue by idelice** [oysandvik94/curl.nvim#21]
### Feature request
When you do `:CurlOpen custom ` followed by `tab` - you should see a dropdown all the custom curls you've created in the past.

### Why
Saves a lot of time - and _thinking_ - which custom curl you need to use, when you can basically do `tab` and go through the list and find the one you need much faster.

**Comment by oysandvik94** [comment]
This will happen soon, thanks for the issue!

**Comment by oysandvik94** [comment]
This can now be done!
I also implemented a picker that uses vim.ui.select(). If you have configured vim.ui.select() with i.e. dressing.nvim then you can fuzzy find over collections with your favourite picker.
There is also an api method that exposes the collections, so that users can create extension for telescope and fzf-lua if they want to. 

I have rewritten the README quite a bit, so documentation is spread throughout, but gist of it is here:
https://github.com/oysandvik94/curl.nvim?tab=readme-ov-file#-collections
