### ISSUE TITLE
Wrong example in Readme

### ISSUE THREAD

**Issue by EricDriussi** [oysandvik94/curl.nvim#22]
Hi there!

I was trying out the plugin and noticed that the [example](https://github.com/oysandvik94/curl.nvim?tab=readme-ov-file#no-quotes-needed) for the "No quotes needed" feature seems to a `SyntaxError` due to an unexpected string in the `JSON`, while removing the `id` part of the request seems to fix it.

So the correct curl seems to be

```bash
curl -X POST https://jsonplaceholder.typicode.com/posts
-H 'Content-Type: application/json'
-d
{
	"title": "now try this"
}
```

I wanted to open a PR with a test case but noticed that none of the tests seem to actually call the `https://jsonplaceholder.typicode.com` API.
Should I open it anyway?

**Comment by oysandvik94** [comment]
I wanted to avoid calling an external api in the tests to avoid instability, so I hoped to create some sort of a integration test that sets up a local api. But I'd be open to just have a test anyway, so feel free to create a PR!

There *might* be a bug related to the syntax thing that I have a fixed in a branch, but I got delayed in finishing it due to holiday, so sorry about that.

**Comment by EricDriussi** [comment]
Yea I'm not a huge fan of calling external apis in tests either.
Since this change would only affect the documentation (the behavior is not broken as far as I can tell) it might be best to just go for a manual test.
